/*
 * Address Book - OpenAPI 3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Runtime.Serialization;

namespace Entities.Dtos
{
     [DataContract]
    public class AssetDto
    {
        ///<summary>
        /// AddressBook id For whom created asset
        ///</summary>
        [DataMember(Name="addressbook-id")]
        public Guid AddressBookId { get; set; }
        ///<summary>
        ///Name of the file
        ///</summary>
        [DataMember(Name="file-name")]
        public string FileName {get; set; }
        ///<summary>
        ///Name of the file
        ///</summary>
        [DataMember(Name="file-type")]
        public string FileType{get; set;}

         /// <summary>
        /// Initializes a new instance of the <see cref="AssetDto" /> class.
        /// </summary>
        /// <param name="File">File.</param>
        public AssetDto(Base64FormattingOptions ImageFile = default(Base64FormattingOptions))
        {
            this.ImageFile = ImageFile;
        }
        
        /// <summary>
        /// Gets or Sets File
        /// </summary>
        [DataMember(Name="file", EmitDefaultValue=false)]
        public Base64FormattingOptions ImageFile { get; set; }

    }
}